<?php

namespace WellnessCoreBundle\Entity;

/**
 * ProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListCatServFromProvider($id)
    {
        /*
         * SELECT categoryservice.name, categoryservice.description
         * FROM provider_categoryservice
         * INNER JOIN categoryservice ON categoryservice.id = provider_categoryservice.categoryservice_id
         * INNER JOIN user ON user.id = provider_categoryservice.provider_id
         * WHERE user.name = "Institut viviane"
         */

        $qb = $this->createQueryBuilder('p');
        $qb->leftJoin('p.categoryservice', 'c');
        $qb->where('p.id =:id');
        $qb->setParameter('id', $id);
        $query = $qb->getQuery();
        $result = $query->getResult();

        return $result;
    }
}
