wellness_admin_users_list:
    path:     /admin/user/list
    defaults: { _controller: WellnessCoreBundle:BackEnd/User:list }

wellness_admin_users_show:
    path:     /admin/user/show/{slug}
    defaults: { _controller: WellnessCoreBundle:BackEnd/User:show }

wellness_admin_users_disable:
    path:     /admin/user/disable
    defaults: { _controller: WellnessCoreBundle:BackEnd/User:disable }


wellness_admin_comment_list:
    path:     /admin/comment/list
    defaults: { _controller: WellnessCoreBundle:BackEnd/Comment:list }

wellness_admin_comment_show:
    path:     /admin/comment/show/{slug}
    defaults: { _controller: WellnessCoreBundle:BackEnd/Comment:show }

wellness_admin_comment_create:
    path:     /admin/comment/create
    defaults: { _controller: WellnessCoreBundle:BackEnd/Comment:create }

wellness_admin_comment_update:
    path:     /admin/comment/update
    defaults: { _controller: WellnessCoreBundle:BackEnd/Comment:update }

wellness_admin_comment_delete:
    path:     /admin/comment/delete
    defaults: { _controller: WellnessCoreBundle:BackEnd/Comment:delete }


wellness_admin_category_list:
    path:     /admin/category/list
    defaults: { _controller: WellnessCoreBundle:BackEnd/Category:list }

wellness_admin_category_show:
    path:     /admin/category/show/{slug}
    defaults: { _controller: WellnessCoreBundle:BackEnd/Category:show }

wellness_admin_category_create:
    path:     /admin/category/create
    defaults: { _controller: WellnessCoreBundle:BackEnd/Category:create }

wellness_admin_category_update:
    path:     /admin/category/update
    defaults: { _controller: WellnessCoreBundle:BackEnd/Category:update }

wellness_admin_category_delete:
    path:     /admin/category/delete
    defaults: { _controller: WellnessCoreBundle:BackEnd/Category:delete }


wellness_admin_newsletter_list:
    path:     /admin/newsletter/list
    defaults: { _controller: WellnessCoreBundle:BackEnd/NewsLetter:list }

wellness_admin_newsletter_show:
    path:     /admin/newsletter/show/{slug}
    defaults: { _controller: WellnessCoreBundle:BackEnd/NewsLetter:show }

wellness_admin_newsletter_create:
    path:     /admin/newsletter/create
    defaults: { _controller: WellnessCoreBundle:BackEnd/NewsLetter:create }

wellness_admin_newsletter_update:
    path:     /admin/newsletter/update
    defaults: { _controller: WellnessCoreBundle:BackEnd/NewsLetter:update }

wellness_admin_newsletter_delete:
    path:     /admin/newsletter/delete
    defaults: { _controller: WellnessCoreBundle:BackEnd/NewsLetter:delete }

wellness_admin_newsletter_send:
    path:     /admin/newsletter/send
    defaults: { _controller: WellnessCoreBundle:BackEnd/NewsLetter:send }


wellness_admin_slider_list:
    path:     /admin/slider/list
    defaults: { _controller: WellnessCoreBundle:BackEnd/Slider:list }

wellness_admin_slider_show:
    path:     /admin/slider/show/{slug}
    defaults: { _controller: WellnessCoreBundle:BackEnd/Slider:show }

wellness_admin_slider_create:
    path:     /admin/slider/create
    defaults: { _controller: WellnessCoreBundle:BackEnd/Slider:create }

wellness_admin_slider_update:
    path:     /admin/slider/update
    defaults: { _controller: WellnessCoreBundle:BackEnd/Slider:update }

wellness_admin_slider_delete:
    path:     /admin/slider/delete
    defaults: { _controller: WellnessCoreBundle:BackEnd/Slider:delete }

wellness_admin_slider_upload:
    path:     /admin/slider/upload
    defaults: { _controller: WellnessCoreBundle:BackEnd/Slider:upload }


wellness_admin_homepage:
    path:     /admin
    defaults: { _controller: WellnessCoreBundle:BackEnd/BackEnd:index }


wellness_public_provider_list:
    path:     /provider/
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Provider:list }

wellness_public_provider_show:
    path:     /provider/show/{slug}
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Provider:show }

wellness_public_provider_search:
    path:     /provider/search
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Provider:search }


wellness_public_category_list:
    path:     /category
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Category:list }

wellness_public_category_show:
    path:     /category/show/{slug}
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Category:show }

wellness_public_category_search:
    path:     /category/search
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Category:search }


wellness_public_homepage:
    path:     /
    defaults: { _controller: WellnessCoreBundle:FrontEnd/FrontEnd:index }

wellness_public_contact:
    path:     /contact
    defaults: { _controller: WellnessCoreBundle:FrontEnd/FrontEnd:contact }

wellness_public_about:
    path:     /about
    defaults: { _controller: WellnessCoreBundle:FrontEnd/FrontEnd:about }

wellness_public_training:
    path:     /training
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Training:list }

wellness_public_promo:
    path:     /promo
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Promo:list }


wellness_public_translationpage:
    path:     /translation
    defaults: { _controller: WellnessCoreBundle:FrontEnd/FrontEnd:translation }



wellness_signin_page:
    path:     /sign-in
    defaults: { _controller: WellnessCoreBundle:Login:signin }

wellness_signup_page:
    path:     /sign-up
    defaults: { _controller: WellnessCoreBundle:Login:signup }


wellness_public_userprofil_show:
    path:     /myaccount/show/{slug}
    defaults: { _controller: WellnessCoreBundle:FrontEnd/UserProfile:showProfil }

wellness_public_userprofil_edit:
    path:     /myaccount/edit
    defaults: { _controller: WellnessCoreBundle:FrontEnd/UserProfile:edit }

wellness_public_userprofil_update:
    path:     /myaccount/update
    defaults: { _controller: WellnessCoreBundle:FrontEnd/UserProfile:update }

wellness_public_userprofil_addtofavorite:
    path:     /myaccount/addtofavorite
    defaults: { _controller: WellnessCoreBundle:FrontEnd/UserProfile:addtofavorite }

wellness_public_userprofil_publishcomment:
    path:     /myaccount/publishcomment
    defaults: { _controller: WellnessCoreBundle:FrontEnd/UserProfile:publishcomment }





