wellness_core_news:
    resource: "@WellnessCoreBundle/Resources/config/routing/news.yml"
    prefix:   /news

back_end:
    resource: "@WellnessCoreBundle/Resources/config/BackEnd/routing.yml"
    prefix:   /admin

front_end:
    resource: "@WellnessCoreBundle/Resources/config/FrontEnd/routing.yml"
    prefix:   /