public_provider_list:
    path:     /provider/
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Provider:index }

public_provider_show:
    path:     /provider/show/{slug}
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Provider:show }

public_provider_search:
    path:     /provider/search
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Provider:search }


public_category_list:
    path:     /category
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Category:index }

public_category_show:
    path:     /category/show/{slug}
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Category:show }

public_category_search:
    path:     /category/search
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Category:search }

public_news_list:
    path:     /news/
    defaults: { _controller: WellnessCoreBundle:FrontEnd/News:index }


public_homepage:
    path:     /
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Home:index }

public_contact:
    path:     /contact
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Home:contact }

public_about:
    path:     /about
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Home:about }

public_training:
    path:     /training
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Training:index }

public_training_show:
    path:     /training/show/{slug}
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Training:show }

public_promo:
    path:     /promotion
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Promo:index }

public_promo_show:
    path:     /promotion/show/{slug}
    defaults: { _controller: WellnessCoreBundle:FrontEnd/Promo:show }


public_translationpage:
    path:     /translation
    defaults: { _controller: WellnessCoreBundle:FrontEnd/FrontEnd:translation }



signin_page:
    path:     /sign-in
    defaults: { _controller: WellnessCoreBundle:Login:signin }

signup_page:
    path:     /sign-up
    defaults: { _controller: WellnessCoreBundle:Login:signup }


public_userprofil_show:
    path:     /myaccount/show/{slug}
    defaults: { _controller: WellnessCoreBundle:FrontEnd/UserProfile:showProfil }

public_userprofil_edit:
    path:     /myaccount/edit
    defaults: { _controller: WellnessCoreBundle:FrontEnd/UserProfile:edit }

public_userprofil_update:
    path:     /myaccount/update
    defaults: { _controller: WellnessCoreBundle:FrontEnd/UserProfile:update }

public_userprofil_addtofavorite:
    path:     /myaccount/addtofavorite
    defaults: { _controller: WellnessCoreBundle:FrontEnd/UserProfile:addtofavorite }

public_userprofil_publishcomment:
    path:     /myaccount/publishcomment
    defaults: { _controller: WellnessCoreBundle:FrontEnd/UserProfile:publishcomment }






