<?php

namespace WellnessCoreBundle\Repository;

/**
 * TrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastListTrainings($maxResult)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->orderBy('t.id', 'DESC');

        if($maxResult!=0){
            $qb->setMaxResults($maxResult);
        }

        $query = $qb->getQuery();
        $result = $query->getResult();

        return $result;
    }
}
